[package]
name = "aztec"
type = "contract"
version = "0.1.0"

[dependencies]
aztec = { git="https://github.com/AztecProtocol/aztec-packages/", tag="v0.77.0", directory="noir-projects/aztec-nr/aztec" }