/**
 * Generate Rust module with VAA constants
 */

import * as fs from "fs";
import * as path from "path";
import { TestVAA, GuardianSet } from "../types";

/**
 * Convert test name to Rust constant name
 */
function toConstName(name: string): string {
  return name.toUpperCase();
}

/**
 * Generate Rust module for a set of VAAs
 */
export function writeVAAsToRust(
  vaas: TestVAA[],
  moduleName: string,
  outputDir: string
): void {
  const lines: string[] = [];

  // File header
  lines.push("// Generated VAA test fixtures");
  lines.push("// DO NOT EDIT - Auto-generated by vaa-generator");
  lines.push("");
  lines.push("#![allow(missing_docs)]");
  lines.push("");

  // Module for this action
  lines.push(`/// ${moduleName} test VAAs`);
  lines.push(`pub mod ${moduleName.toLowerCase().replace(/ /g, "_")} {`);
  lines.push("");

  // Generate constants
  for (const vaa of vaas) {
    const constName = toConstName(vaa.name);
    lines.push(`    /// ${vaa.description}`);
    lines.push(`    /// Expected: ${vaa.expectedResult}${vaa.expectedError ? ` - ${vaa.expectedError}` : ""}`);
    lines.push(`    pub const ${constName}: &str = "${vaa.vaa.base64}";`);
    lines.push("");
  }

  lines.push("}");
  lines.push("");

  const filename = `${moduleName.toLowerCase().replace(/ /g, "_")}_vaas.rs`;
  const filepath = path.join(outputDir, filename);

  fs.writeFileSync(filepath, lines.join("\n"));
  console.log(`✅ Generated Rust module → ${filepath}`);
}

/**
 * Generate Rust module for guardian keys
 */
export function writeGuardianKeysToRust(
  guardianSet: GuardianSet,
  outputDir: string
): void {
  const lines: string[] = [];

  lines.push("// Generated guardian keys for testing");
  lines.push("// DO NOT EDIT - Auto-generated by vaa-generator");
  lines.push("");
  lines.push("#![allow(missing_docs)]");
  lines.push("");
  lines.push("use soroban_sdk::{Env, Vec, BytesN};");
  lines.push("");
  lines.push("/// Test guardian Ethereum addresses (20 bytes each)");
  lines.push("pub const TEST_GUARDIAN_ADDRESSES: [&str; 19] = [");

  for (const guardian of guardianSet.guardians) {
    const addrWithout0x = guardian.ethereumAddress.replace("0x", "");
    lines.push(`    "${addrWithout0x}",`);
  }

  lines.push("];");
  lines.push("");
  lines.push("/// Get test guardian set for contract initialization");
  lines.push("pub fn get_test_guardian_set_0(env: &Env) -> Vec<BytesN<20>> {");
  lines.push("    let mut keys = Vec::new(env);");
  lines.push("    for addr_str in TEST_GUARDIAN_ADDRESSES.iter() {");
  lines.push("        let bytes = hex::decode(addr_str).unwrap();");
  lines.push("        let mut arr = [0u8; 20];");
  lines.push("        arr.copy_from_slice(&bytes);");
  lines.push("        keys.push_back(BytesN::<20>::from_array(env, &arr));");
  lines.push("    }");
  lines.push("    keys");
  lines.push("}");
  lines.push("");

  const filepath = path.join(outputDir, "test_guardians.rs");
  fs.writeFileSync(filepath, lines.join("\n"));
  console.log(`✅ Generated guardian Rust module → ${filepath}`);
}
